spring:
  application:
    name: rate-limiter-test
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
server:
  port: 10087
logging:
  file:
    name: ${spring.application.name}.log
    path: log
